#!/bin/bash
# Written by Dennis Cole III
# Clear LTechAgent State on Linux
# This script checks for "Failed to unencrypt LabTech agent password",
# "Failed to read agent state file" and "Failed to read old agent state file"
#
# If found, it deletes the state files in the ltechagent folder and restarts
# agent.
# This can be run as a regular script
# This script is not written by, nor supported by ConnectWise
#
# Version 0.2.2 - There was an issue with looping the Error Check strings
# Version 0.2.1 - added additional error strings to check


# Check if running as root and exit if not
if [[ $EUID -ne 0 ]]
then
  echo "This script must be run as root.."
  exit 1
fi

# Functions
# Announce says what's happening and hides output
function announce {
        >&2 echo -n "$1"
}

# Check_fail checks status of command and exits if it fails
function check_fail {
        if [[ $1 -ne 0 ]]; then
                >&2 echo "FAIL!"
                exit 1
        else
                >&2 echo "OK!"
        fi
}

# Variable Checks
LTDIR="/usr/local/ltechagent"
AGENT_LOG="$LTDIR/agent.log"
STATE_FILE="$LTDIR/state"
STATE_OLD_FILE="$LTDIR/state_old"
LTSVC="ltechagent.service"
ERROR_CHECK_STRINGS=("Failed to unencrypt LabTech agent password."
                    "Failed to read agent state file")
# This line is not quite working                    "Failed to read old agent state file")

# Start of script
echo "**********************************************************************"
echo "Script ${0##*/} has started"

# Trying to verify if LTechAgent is installed
if [[ ! -d $LTDIR ]]
then
  echo "LTechAgent is not installed.."
  exit 1
fi

# Verify there is an agent log
if [[ ! -f $AGENT_LOG ]]
then
  echo "No agent log found.."
  exit 1
fi

AGENT_ISSUE_FOUND=false

while read -r line
do
  for ((i = 0; i < ${#ERROR_CHECK_STRINGS[@]}; i++))
  do
    ERR=${ERROR_CHECK_STRINGS[$i]}
    if [[ "$line" == *"$ERR"* ]]
    then
      AGENT_ISSUE_FOUND=true
      LAST_FOUND_ERROR=$ERR
    fi
  done
done < <(tail $AGENT_LOG)

if [[ "$AGENT_ISSUE_FOUND" == "true" ]]
then
  echo "At least one error was found. Last error: $LAST_FOUND_ERROR"
  echo "Agent is not working. Working to fix now."

  announce "Stopping LTechAgent Agent.."
  systemctl stop $LTSVC
  check_fail $?

  announce "Removing state file.."
  rm -f $STATE_FILE
  check_fail $?

  announce "Removing state_old file.."
  rm -f $STATE_OLD_FILE
  check_fail $?

  announce "Starting LTechAgent.."
  systemctl start $LTSVC
  check_fail $?
else
  echo "No recent errors were found that can be fixed with this script."
  echo "If you are still having an issue, you may need to do addtional troubleshooting"
fi

# End of script
echo "All tasks complete."
echo "Please check if the agent is running in Automate (LabTech)."
echo "Script ${0##*/} has ended"
echo "**********************************************************************"
